/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mishal;

/**
 *
 * @author Mish
 */
public class StudentUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentUI
     */
    public StudentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtfNIC = new javax.swing.JTextField();
        jtfStudentID = new javax.swing.JTextField();
        jtfStudentName = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfTelephoneNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcmbBatchNo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jcbDORDAY = new javax.swing.JComboBox();
        jcbDORMONTH = new javax.swing.JComboBox();
        jcbDORYEAR = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jcbDOBDAY = new javax.swing.JComboBox();
        jcbDOBMONTH = new javax.swing.JComboBox();
        jcbDOBYEAR = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jrbFemale = new javax.swing.JRadioButton();
        jrbMale = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jtfAssignment3 = new javax.swing.JTextField();
        jtfAssignment1 = new javax.swing.JTextField();
        jtfAssignment2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Marks");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 540, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 80, 80, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 120, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 160, 50, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 210, 25, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 250, 24, 30);

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 650, 80, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("Save");
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 500, 80, 30);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 550, 80, 30);
        jPanel1.add(jtfNIC);
        jtfNIC.setBounds(250, 200, 110, 30);
        jPanel1.add(jtfStudentID);
        jtfStudentID.setBounds(249, 70, 110, 30);
        jPanel1.add(jtfStudentName);
        jtfStudentName.setBounds(250, 120, 110, 30);
        jPanel1.add(jtfAddress);
        jtfAddress.setBounds(250, 160, 110, 30);
        jPanel1.add(jtfEmail);
        jtfEmail.setBounds(250, 390, 190, 30);

        jtfTelephoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTelephoneNumKeyTyped(evt);
            }
        });
        jPanel1.add(jtfTelephoneNum);
        jtfTelephoneNum.setBounds(250, 300, 110, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Assignment 3");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 660, 90, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telephone Num");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 300, 110, 30);

        jcmbBatchNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Batch 80", "Batch 81", "Batch 82", "Batch 83", "Batch 84 ", "Batch 85" }));
        jPanel1.add(jcmbBatchNo);
        jcmbBatchNo.setBounds(250, 350, 110, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 510, 50, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Assignmet 1");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 580, 90, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Assignment 2");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 620, 90, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Batch No");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 350, 60, 30);
        jPanel1.add(jtfAge);
        jtfAge.setBounds(250, 250, 190, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 390, 40, 30);

        jcbDORDAY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jcbDORDAY);
        jcbDORDAY.setBounds(250, 470, 60, 20);

        jcbDORMONTH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "September", "Octuber", "November", "December" }));
        jPanel1.add(jcbDORMONTH);
        jcbDORMONTH.setBounds(320, 470, 77, 20);

        jcbDORYEAR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(jcbDORYEAR);
        jcbDORYEAR.setBounds(420, 470, 60, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DOB");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 430, 40, 30);

        jcbDOBDAY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jcbDOBDAY);
        jcbDOBDAY.setBounds(250, 430, 60, 20);

        jcbDOBMONTH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "September", "Octuber", "November", "December" }));
        jPanel1.add(jcbDOBMONTH);
        jcbDOBMONTH.setBounds(320, 430, 77, 20);

        jcbDOBYEAR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(jcbDOBYEAR);
        jcbDOBYEAR.setBounds(420, 430, 60, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DOR");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 470, 40, 30);

        jrbFemale.setText("Female");
        jPanel1.add(jrbFemale);
        jrbFemale.setBounds(320, 510, 60, 23);

        jrbMale.setText("Male");
        jPanel1.add(jrbMale);
        jrbMale.setBounds(250, 510, 60, 23);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Insert Student Information");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(150, 10, 290, 30);
        jPanel1.add(jtfAssignment3);
        jtfAssignment3.setBounds(250, 660, 120, 20);
        jPanel1.add(jtfAssignment1);
        jtfAssignment1.setBounds(250, 580, 120, 20);
        jPanel1.add(jtfAssignment2);
        jtfAssignment2.setBounds(250, 620, 120, 20);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 600, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mish\\Desktop\\YURRRRRR\\Work\\HND\\Assignments\\Object Oriented Programming\\Mishal 85-35\\System\\Images\\StudentUI2.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Main obj = new Main();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jtfStudentID.setText(null);
        jtfStudentName.setText(null);
        jtfAddress.setText(null);
        jtfNIC.setText(null);
        jtfAge.setText(null);
        jtfTelephoneNum.setText(null);
        jtfEmail.setText(null);
        jtfAssignment1.setText(null);
        jtfAssignment2.setText(null);
        jtfAssignment3.setText(null);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfTelephoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTelephoneNumKeyTyped
        // Allow Numbers Only:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
    }
    }//GEN-LAST:event_jtfTelephoneNumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbDOBDAY;
    private javax.swing.JComboBox jcbDOBMONTH;
    private javax.swing.JComboBox jcbDOBYEAR;
    private javax.swing.JComboBox jcbDORDAY;
    private javax.swing.JComboBox jcbDORMONTH;
    private javax.swing.JComboBox jcbDORYEAR;
    private javax.swing.JComboBox jcmbBatchNo;
    private javax.swing.JRadioButton jrbFemale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfAge;
    private javax.swing.JTextField jtfAssignment1;
    private javax.swing.JTextField jtfAssignment2;
    private javax.swing.JTextField jtfAssignment3;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNIC;
    private javax.swing.JTextField jtfStudentID;
    private javax.swing.JTextField jtfStudentName;
    private javax.swing.JTextField jtfTelephoneNum;
    // End of variables declaration//GEN-END:variables
}
